### PR TITLE
Remove patch

### PR DESCRIPTION
**Pull request by ocefpaf**
Latest `conda-build` should do the right thing without the need for the patch.

Ping @pmlandwehr who has a few similar too.

### CODE REVIEW

**Comment by ocefpaf** [comment]
https://github.com/conda/conda-build/pull/1146 works flawlessly :tada: 

Thanks @minrk and @msarahan for this. It will make our lives in `conda-forge` much easier!

**Comment by mattexx** [comment]
I'm seeing conda build failures in packages with pexpect 4.2.0 and python 2. Is there any reason you removed the `no_async.patch`? We're having to pin to 4.1.0 to unblock our conda builds.

**Comment by ocefpaf** [comment]
Latest conda does not need that patch to build. Maybe you need to update your conda locally. If that does not work post the details of the failure here.

**Comment by mattexx** [comment]
Thanks for the tip @ocefpaf .. `conda update conda-build` did the trick!

**Comment by ocefpaf** [comment]
Glad it is resolved. That `patch` was an ugly hack to start with. We are better now with `conda-build`'s new behavior.

**Comment by mattexx** [comment]
Agreed!

**Comment by SylvainCorlay** [comment]
@minrk @ocefpaf it seems that this broke some recipes that depend on pexpect. 
https://github.com/conda-forge/bqplot-feedstock/pull/7

**Comment by ocefpaf** [comment]
@SylvainCorlay you have to rerender to get the latest conda-build and your build should be fine.

**Comment by SylvainCorlay** [comment]
how do I rerender?

**Comment by ocefpaf** [comment]
Install conda-smithy and type:

conda smithy rerender

at the root feedstock directory.

On Aug 17, 2016 3:29 PM, "Sylvain Corlay" <notifications@github.com> wrote:

how do I rerender?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/pexpect-feedstock/pull/5#issuecomment-240503723>,
or mute the thread

**Pull request merged**
